spring:
  data:
    mongodb:
      primary:
        host: localhost
        port: 27017
        uri: mongodb://localhost:27017/gmsk-cc
        database: gmsk-cc
      secondary:
        host: localhost
        port: 27017
        uri: mongodb://localhost:27018/gmsk-cc2
        database: gmsk-cc2